---
- hosts: 34.71.255.226
  name: Ansible tasks for project 1
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - apache2 
          - php
          - php-xml

    - name: Check if disk exists
      shell: "file -sL /dev/disk/by-id/goggle-persistent-disk-1"
      register: disk_exists

    - name: Format disk
      shell: "mkfs.ext4 /dev/disk/by-id/google-persistent-disk-1"
      when: "'UUID=' not in disk_exists.stdout"

    - name: Mount drive
      mount:
        path: "/var/www/html"
        src: "/dev/disk/by-id/google-persistent-disk-1"
        fstype: ext4
        opts: discard,defaults
        state: mounted

        #    - name: Download Tomcat using get_url
        #      become: yes
        #      get_url:
        #        url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        #        dest: /var/www/html
        #        mode: 0755
        #        group: www-data
        #        owner: www-data

    - name: Unarchives the tar


        #    - name: Change html dir ownership
        #      file:
        # path: /var/www/html
        # state: directory
        # owner: www-data
        # group: www-data
        # mode: "0770"
     
            #    - name: Unarchives the zip file
            #         unarchive:
            #         src: /test1/project.zip
            #         dest: /test2

