---
- hosts: 34.71.255.226
  name: Ansible tasks for project 1
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - apache2 
          - php
          - php-xml
      
    - name: Create a ext4 filesystem on data disk     
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb

    - name: Mount drive
      mount:
        path: "/var/www/"
        src: "/dev/disk/by-id/google-persistent-disk-1"
        fstype: ext4
        opts: discard,defaults
        state: mounted

    - name: Creates directory
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: 0750
    
    - name: Unarchives the tar
      unarchive:
        src: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /var/www/html
        owner: www-data
        group: www-data
        mode: 0770
        remote_src: True

    - name: Enable service httpd and ensure it is not masked
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
        masked: no
